version: '3.8'
services:
  db:
    image: postgres:15
    container_name: loginguard-db
    environment:
      POSTGRES_DB: loginguard
      POSTGRES_USER: jack
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"